//FOR INTERVIEW THIS IS BASIC CONCEPT OF ASYNCHRONOUS PROGRAMMING IN JAVASCRIPT, 
// IT IS IMPORTANT TO UNDERSTAND HOW CALLBACKS WORK IN JAVASCRIPT TO HANDLE ASYNCHRONOUS OPERATIONS LIKE API CALLS, FILE READING, ETC.
//  IN THIS EXAMPLE, WE ARE SIMULATING A LONG RUNNING TASK USING setTimeout AND THEN USING A CALLBACK FUNCTION TO GET THE STATUS BACK TO THE MAIN THREAD ONCE THE TASK IS COMPLETED.

/*console.log("start");
function dowork() {
    setTimeout(() => {
        console.log("doing work");
    }, 3000);
}
dowork();
console.log("end");
*/
//QUESTION 1-WHY WE NEED ASCHYNOROUS TYPE OF CODING 
//WHAT IS CALL BACK FUNCTION - AND HOW WE CAN USE IT TO GRAB CALL
//CALLBACK
console.log("start");
function dowork(CB) {
    setTimeout(() => { // RETURN WAS NOT WORKING SO WE USED CALLBACK FUNCTION TO GET THE STATUS BACK TO THE MAIN THREAD
        CB("WORKING"); //THIS GET OUT OF THE THREAD FOR 3 SECONDS AND THEN CALLS THE CALLBACK FUNCTION WITH THE STATUS "WORKING"
    }, 3000);          //
}
dowork((status) => {
    console.log("work is done with status:", status);
});
console.log("end");
